name: Release Manifest
on:
  push:
    branches:
      - main
jobs:
  version:
    name: Version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump manifest
        run: scripts/bump_version.sh
      - name: Commit manifest
        run: |
          git config user.name 'release'
          git config user.email 'release@foo.com'
          git commit -am "Manifest bumped"
          git push
