name: Release Manifest
on:
  push:
    branches:
      - main
jobs:
  version:
    name: Version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump manifest
        run: scripts/bump_version.sh
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: manifest.json
          commit-message: manifest bumped
          branch: bump_manifest
          delete-branch: true
      - uses: reitermarkus/automerge@v2
        with:
          merge-method: squash
          squash-commit-title: "[skip ci] ${{ steps.cpr.outputs.pull-request-number }} Automerge Bump Manifest"
          pull-request: ${{ steps.cpr.outputs.pull-request-number }}
          
